### ISSUE TITLE
strange warning about project not being in a git repository?

### ISSUE THREAD

**Issue by peterfigure** [JavierSegoviaCordoba/semver-gradle-plugin#22] opened 2021-12-12 17:51 UTC
doesn't appear to impact anything but does print a warning in this multi-module project

```
> Task :config-versioning:generatePrecompiledScriptPluginAccessors
semver plugin can't work if the project is not a git repository <============== HERE

> Task :config-versioning:compileKotlin
w: Language version 1.4 is deprecated and its support will be removed in a future version of Kotlin

BUILD SUCCESSFUL in 9s
81 actionable tasks: 40 executed, 41 up-to-date

gradle-plugins on  main [!] via ☕ v11.0.13 via 🅺 on ☁️  (us-west-2) on ☁️ xxx(us-east1) took 9s 
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .github/workflows/pushpr.yaml
	modified:   config-versioning/build.gradle.kts
	modified:   config-versioning/src/main/kotlin/com.xxx.gradle.config-versioning.gradle.kts

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by JavierSegoviaCordoba** [comment] 2021-12-12 18:14
That was the fix for this one https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/issues/18

Is it appearing even if the project is a git repository?

**Comment by peterfigure** [comment] 2021-12-12 18:16
it appears so :( see `git status` output

**Comment by JavierSegoviaCordoba** [comment] 2021-12-12 18:16
I can't reproduce it in my repositories, can you share a repro?

**Comment by peterfigure** [comment] 2021-12-12 18:18
private repo unfortunately, I'll try to put together another repo and see if it replicates the problem

**Comment by JavierSegoviaCordoba** [comment] 2021-12-12 20:25
Fixed, if a tag is pushed two times, the task will fail (which is normal). Now instead of checking if there is a crash, plugin checks if `.git`exists.

**Closed by JavierSegoviaCordoba** 2021-12-12 20:25 UTC
