### ISSUE TITLE
Overriding the version seems to be broken

### ISSUE THREAD

**Issue by tkrah** [JavierSegoviaCordoba/semver-gradle-plugin#175] opened 2024-10-07 14:18 UTC
I tried to override the version like described here (using Gradle 8.10.2):

https://github.com/JavierSegoviaCordoba/semver-gradle-plugin?tab=readme-ov-file#override-the-version

```
semver {
    version.set("1.0.0")
}
```

does not work and fails with a gradle error:

```
No signature of method: com.javiersc.semver.project.gradle.plugin.VersionProperty.set() is applicable for argument types: (String) values: [1.0.0]
  Possible solutions: get(), get(), getAt(java.lang.String), use([Ljava.lang.Object;), wait(), grep()
```

So I tried:

```
semver {
	setVersion("1.0.0")
}
```

which does not fail but it just gets ignored, printSemVer task still does print its calculated version number:

`semver for sub1: 0.1.0.0+195c209+DIRTY`

instead of the expected:

`semver for sub1: 1.0.0`

I am lost here, how to override the version, it seems not to work at all.

**Comment by JavierSegoviaCordoba** [comment] 2024-10-07 14:39
I will recheck but I think I deleted that method some time ago due some order problems.

As workaround you can use `mapVersion`.

Thank you for reporting this, I will update the docs 😄

**Comment by JavierSegoviaCordoba** [comment] 2024-10-07 14:41
About `+DIRTY`, it is shown when the repository has some uncommitted changes, you can pass `-P semver.checkClean=false` (or set it on `gradle.properties`).

**Comment by tkrah** [comment] 2024-10-07 14:51
> I will recheck but I think I deleted that method some time ago due some order problems.
> 
> As workaround you can use `mapVersion`.
> 
> Thank you for reporting this, I will update the docs 😄

Do you have an example for the mapVersion syntax to override it, the example from the docs is failing for me too or I am just unable to get the syntax right.

**Comment by JavierSegoviaCordoba** [comment] 2024-10-07 14:54
You can see it in this test:

https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/blob/main/semver-project-gradle-plugin/testFunctional/resources/version-mapping/v1_0_0%20to%20v1_0_0+1_9_0/build.gradle.kts

**Comment by tkrah** [comment] 2024-10-07 14:56
> You can see it in this test:
> 
> https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/blob/main/semver-project-gradle-plugin/testFunctional/resources/version-mapping/v1_0_0%20to%20v1_0_0+1_9_0/build.gradle.kts

This fails for me with:

```
> Could not create task ':printSemver'.
   > Could not isolate value com.javiersc.semver.project.gradle.plugin.valuesources.VersionValueSource$Params_Decorated@2b159202 of type VersionValueSource.Params
      > Could not serialize value of type $Proxy208

```

Using:

```
semver {
	mapVersion { gradleVersion ->
		"${gradleVersion.copy(metadata = "1.1.0")}"
	}
}

```

**Comment by JavierSegoviaCordoba** [comment] 2024-10-07 15:43
Is it your project open source?

I would need a reproducer but it look likes an issue with configuration cache or project isolation.

I haven't tested my plugin with isolated projects so it is possible I may update it to support IP. If you confirm you have it enabled I can try to take a look into it this week.

**Comment by tkrah** [comment] 2024-10-07 16:18
It is just a mini playground locally, nothing fancy. I post a link to a sample github repo asap - I just did what you wrote in the docs under apply the plugin, the second proposal, applied from settings.gradle:
```

pluginManagement {
	plugins {
		id 'com.javiersc.semver' version '0.7.1'
	}
}

plugins {
	id 'com.javiersc.semver'
}
```

**Comment by JavierSegoviaCordoba** [comment] 2024-10-07 16:19
@tkrah I can reproduce it. For some reason, the test with configuration cache is passing but on a real project I am getting the issue you have reported.

**Comment by JavierSegoviaCordoba** [comment] 2024-10-07 16:31
@tkrah the reproducer I have is failing due I was capturing a value that has `Project` as a reference.

```kotlin
semver {
    mapVersion { gradleVersion ->
        val isDirty: Boolean = gradleVersion.metadata == "DIRTY"
        val metadata: String =
            if (isDirty) "${getKotlinPluginVersion()}+DIRTY" else getKotlinPluginVersion()
        "${gradleVersion.copy(metadata = metadata)}"
    }
}
```

It can be fixed by extracting the calculation of `getKotlinPluginVersion()` outside of `mapVersion`

```kotlin
semver {
    mapVersion { gradleVersion ->
        val isDirty: Boolean = gradleVersion.metadata == "DIRTY"
        val metadata: String =
            if (isDirty) "${getKotlinPluginVersion()}+DIRTY" else getKotlinPluginVersion()
        "${gradleVersion.copy(metadata = metadata)}"
    }
}
```

Can you share your reproducer? I have tried to do the next but it is working without issues on my side.

```kotlin
semver {
    mapVersion { "1.0.0" }
}
```

**Comment by tkrah** [comment] 2024-10-07 17:08
@JavierSegoviaCordoba https://github.com/tkrah/semver-gradle-plugin-playground here you go.

**Comment by JavierSegoviaCordoba** [comment] 2024-10-07 18:21
@tkrah the problem is related to using Groovy in the `build.gradle` files instead of using Kotlin and `build.gradle.kts`.

I will try to fix it.

**Comment by tkrah** [comment] 2024-10-07 18:50
Bummer, that's interesting, I was under the impression that it should not matter (from a users perspective) if I use groovy or kotlin - unfortunately I have a groovy destination and I am unable to migrate the whole stack to kotlin at the moment. I hope you can fix that, thx.

**Comment by tkrah** [comment] 2024-10-08 10:08
I tried that workaround @JavierSegoviaCordoba - see [here](https://github.com/tkrah/semver-gradle-plugin-playground/tree/ISSUE-175-WORKAROUND), but the version is still wrong in the subprojects:


```
> Task :printSemver
semver for semver-gradle-plugin-playground: 1.0.0

> Task :sub1:printSemver
semver for sub1: 0.1.0.0+1cf0ef9

> Task :sub2:printSemver
semver for sub2: 0.1.0.0+1cf0ef9

BUILD SUCCESSFUL in 668ms
9 actionable tasks: 7 executed, 2 from cache
```

Something is still not right, suggestions?

**Comment by JavierSegoviaCordoba** [comment] 2024-10-08 10:44
Have you put the workaround in each subproject? Each project is independent including the root project one.

Another option is to do it on the settings script with a combination of the `beforeProject` and the `withPlugin` callbacks. So you don't need to put the workaround on each project.

I will share the code later when I come back to home.

**Comment by JavierSegoviaCordoba** [comment] 2024-10-08 10:46
This would be a good feature request for the settings plugin to avoid adding the manual boilerplate I commented before.

**Comment by tkrah** [comment] 2024-10-08 10:54
I tried:

```
allprojects {
	pluginManager.withPlugin('com.javiersc.semver') {
		semver {
			mapVersion Map.per
		}

	}
}
```

but this did not work.

**Comment by JavierSegoviaCordoba** [comment] 2024-10-08 11:24
@tkrah can you try to do this on the `settings.gradle`?

```Groovy
import com.javiersc.gradle.version.GradleVersion
import com.javiersc.semver.project.gradle.plugin.SemverExtension
import com.javiersc.semver.project.gradle.plugin.SemverExtension.VersionMapper

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id("com.javiersc.semver") version "0.7.1"
}

dependencyResolutionManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

class Map {
    static per = new VersionMapper() {
        @Override
        String map(GradleVersion gradleVersion) {
            "1.0.0"
        }
    }
}

gradle.beforeProject { project ->
    project.pluginManager.withPlugin('com.javiersc.semver') {
        project.extensions.configure(SemverExtension) { semver ->
            semver.mapVersion Map.per
        }
    }
}
```

**Comment by JavierSegoviaCordoba** [comment] 2024-10-08 11:26
@tkrah the problem is, that it is not working if the plugin is not explicitly applied on each subproject.

I will need to revisit the settings plugin as this is a bug for sure.

**Comment by tkrah** [comment] 2024-10-08 11:29
> @tkrah the problem is, that it is not working if the plugin is not explicitly applied on each subproject.
> 
> I will need to revisit the settings plugin as this is a bug for sure.

Yeah that was my observation too, with your proposal in the settings.gradle I need to add:

id 'com.javiersc.semver'

to every build.gradle in my project to have it working.

**Comment by tkrah** [comment] 2024-10-08 11:32
And another thing, the workaround moves that to a static context which is a problem, because my goal is this:

```
semver {
    mapVersion { determineVersion() }
}
```

Where  determineVersion() is something like:

```
static String evaluateProjectVersion() {
	if (System.env.BUILD_NUMBER != null) {
		version = version.toString().replaceAll("\\+.*", "+build${String.format("%05d", Integer.parseInt(System.env.BUILD_NUMBER as String))}")
	}
	logger.lifecycle("${project.name} Version ${project.version}")
	return version
}
```

This is not possible in the settings.xml because I can't use project from a static context.

**Comment by JavierSegoviaCordoba** [comment] 2024-10-08 12:14
@tkrah

It is not necessary, the problem is I am using a synthetic ID on the projects ("com.javiersc.semver.project"), so to get the workaround working it is necessary to do:

```
gradle.beforeProject { project ->
    project.pluginManager.withPlugin('com.javiersc.semver.project') {
        project.extensions.configure(SemverExtension) { semver ->
            semver.mapVersion Map.per
        }
    }
}
```

I will improve this to not having to know that ID and just use only the one main one.

About the static issue, this code is picking and changing the `project.version`? You should avoid doing anything with `project.version` and do everything with `mapVersion` function.

```
version = version.toString().replaceAll("\\+.*", "+build${String.format("%05d", Integer.parseInt(System.env.BUILD_NUMBER as String))}")
```

Here you can get the version (and you can do `toString`) to do the replacements you are doing on the `evaluateProjectVersion` method:

class Map {
    static per = new VersionMapper() {
        @Override
        String map(GradleVersion gradleVersion) {
            gradleVersion.toString() // do whatever you need with it
        }
    }
}

gradle.beforeProject { project ->
    project.pluginManager.withPlugin('com.javiersc.semver.project') {
        project.extensions.configure(SemverExtension) { semver ->
            semver.mapVersion Map.per
        }
    }
}

**Comment by tkrah** [comment] 2024-10-08 12:28
@JavierSegoviaCordoba Gotcha, thanks - that synthetic id is tricky - got the workaround working now, including your proposal of the version mapper. Thanks for your support.

**Comment by JavierSegoviaCordoba** [comment] 2024-10-08 13:31
@tkrah I have removed the synthetic IDs, so everything will use the `com.javiersc.semver` ID.

Furthermore, I have added the `semver` extension to the settings file, so you will be able to remove some boilerplate with the next version, 0.8.0:

```groovy
// settings.gradle.kts
class SemverWorkaround {
    static mapper = new VersionMapper() {
        @Override
        String map(GradleVersion gradleVersion) {
            "1.0.0"
        }
    }
}

semver {
    mapVersion SemverWorkaround.mapper
}
```

If you want to test it before the version 8.0.0 is released, you can test the version `0.7.2-SNAPSHOT`. It is in the snapshot repository.

The workaround has been added to the README as well.

I will keep this issue open until I get a reply from Gradle engineers [here](https://github.com/gradle/gradle/issues/30830).

**Comment by tkrah** [comment] 2024-10-08 14:26
@JavierSegoviaCordoba I would like to try the changes ... but which snapshot repository do you refer to here (sorry if that is obvious, I don't know it yet).

**Comment by JavierSegoviaCordoba** [comment] 2024-10-08 15:25
@tkrah you need to add `maven("https://oss.sonatype.org/content/repositories/snapshots")` to the `repositories` blocks

**Comment by tkrah** [comment] 2024-10-08 16:21
Thx, works like you told :).

**Comment by sureshg** [comment] 2024-10-08 20:31
@JavierSegoviaCordoba i am also facing `couldn't serialize` issue with `build-logic` convention plugins. I hope `0.8.0` would fix this problem too..rt? 

```
A problem occurred configuring root project 'build-commons'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not isolate value com.javiersc.semver.project.gradle.plugin.valuesources.VersionValueSource$Params_Decorated@472a3c41 of type VersionValueSource.Params
      > Could not serialize value of type Settings_repo_settings_gradle....

```

**Comment by JavierSegoviaCordoba** [comment] 2024-10-08 20:38
@sureshg do you have some repro? Based on the error, `Settings_repo_settings_gradle`, it is possible that you are adding some reference to `Settings` or something similar inside the `mapVersion` block. If you take that outside `mapVersion` it should work:

```kotlin
// does not work
semver {
    mapVersion {
        extensions... // extensions hold `Settings`
    }
}
```

```kotlin
// should work
semver {
    val whatever = extensions...
    mapVersion {
        whatever 
    }
}
```

**Comment by sureshg** [comment] 2024-10-08 21:32
Yes, this is what i am doing in `settings.repo.settings.gradle.kts` inside build-logic 

```kotlin
gradle.beforeProject {
  pluginManager.withPlugin("com.javiersc.semver.project") {
    configure<SemverExtension> {
      mapVersion {
        versionCatalog.getString("kotlin").orEmpty()
      }
    }
  }
}
```

**Comment by JavierSegoviaCordoba** [comment] 2024-10-08 22:25
I will try tomorrow but I am pretty sure that the `versionCatalog` receiver is `Project` or something similar that cannot be serialized.

You must extract it outside of the `mapVersion` block as it is not something I can fix from my side.

I would like that Gradle provides some linter or checker to warn about those usages as the error is not easy to understand...

**Comment by sureshg** [comment] 2024-10-08 23:03
@JavierSegoviaCordoba thanks..extracting out of mapversion worked. When are you planning to release 0.8.0? Would love to use the extension instead of this beforeProject trickery.

**Comment by sureshg** [comment] 2024-10-09 14:00
Thanks for releasing `0.8.0`. Any idea why [semver extension](https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/blob/main/semver-settings-gradle-plugin/main/kotlin/com/javiersc/semver/settings/gradle/plugin/SemverSettingsPlugin.kt#L13) is not available on settings convention plugin. Gradle build and IntelliJ sync throw the following error

```kotlin
e: file:///xxxx/build-logic/src/main/kotlin/settings.repo.settings.gradle.kts:42:1 Expression 'semver' cannot be invoked as a function. The function 'invoke()' is not found
```
By the way, it available in `settings.gradle.kts` file as expected.

**Comment by JavierSegoviaCordoba** [comment] 2024-10-09 14:10
Gradle added recently the accessors generation in Gradle 8.8 for settings plugin extensions, but I don't know if that works for convention plugins.

As a workaround you can do 

```kotlin

configure<SemverSettingsExtension> {
    ...
}
```

**Comment by JavierSegoviaCordoba** [comment] 2024-12-29 17:55
Closing this issue as I have provided the relevant fixes that were on my part and shared a workaround for the problems with Groovy that should be fixed by Gradle folks.

If I am missing something, ping me and I will reopen it 😄

**Closed by JavierSegoviaCordoba** 2024-12-29 17:55 UTC
Labels: bug, blocked, has-workaround
